### ISSUE TITLE
HOTA barb broken

### ISSUE THREAD

**Issue by Neretil** [BosslandGmbH/Trinity#13]
Hai, i came back to check the HOTA update but can't see any changes. With the built in IK-HOTA build the bot still spends half the time running/jiggling around a few yards up and down instead of hammering the mobs. 

Fresh install, latest Trinity files, Furious Charge set to 6 seconds and mob desnsity 10.

**Comment by Nesox** [comment]
I will take a look

**Comment by Nesox** [comment]
Should be fixed now
