### ISSUE TITLE
Item Stashing

### ISSUE THREAD

**Issue by xxxAlpha71xxx** [BosslandGmbH/Trinity#9]
Trinity now seems to stash Jesseth Skullscythe but with the update also seems to be stashing ANY Jesseth Skullshield.  I have ancient only selected and had three non ancients in my stash this morning.

**Comment by ReddeR1337** [comment]
https://github.com/BosslandGmbH/Trinity/pull/8
All fixed on my Fork version, just wait pull request accept

**Comment by Nesox** [comment]
It's fixed in #14
